/**
 * All user-facing strings live here so we can swap to a different locale
 * (e.g. Vietnamese) without touching components.
 */
export const strings = {
  app: {
    title: 'Strategy Builder',
    subtitle: 'Design, configure and export your trading bot strategy.',
  },
  header: {
    botNamePlaceholder: 'Untitled bot',
    backtest: 'Backtest',
    export: 'Export',
    saved: 'Saved',
    saving: 'Saving…',
    secondsAgo: (s: number) => `${s}s ago`,
  },
  cypheus: {
    panelTitle: 'Cypheus',
    tabLabel: 'Chat',
    jsonTabLabel: 'JSON',
    inputPlaceholder: "Tell Cypheus what you're building...",
    send: 'Send',
    createNewBot: 'Create new bot',
    confirmReset: {
      title: 'Start a new bot?',
      body: 'Your current configuration will be cleared.',
      confirm: 'Start over',
      cancel: 'Cancel',
    },
    greeting: {
      hello: "Hi, I'm Cypheus.",
      pitch:
        "I'll help you build your first trading bot. Tell me what you have in mind.",
    },
    magicBuild: {
      ack: 'Got it. Let me build a Bollinger Breakout strategy on BTC-USDC for you.',
      note: 'Note: This is demo content prepared to showcase the AI flow.',
      step1: 'Setting up bot configuration...',
      step1Comment:
        'BTC-USDC offers high liquidity. 5-minute timeframe is ideal for scalping.',
      step2: 'Defining entry conditions...',
      step2Comment:
        'RSI below 30 signals oversold – a classic buy entry.',
      step3: 'Going Long with Market orders for fast fills.',
      step4: 'Setting take-profit and stop-loss.',
      step4Comment:
        '5% take-profit at half position, another 25% at 10% profit. 3% stop-loss.',
      doneA: 'All set.',
      doneB:
        'Review the JSON in the {} JSON tab, then click Export when ready.',
      pinnedFooter: 'Cypheus is configuring...',
      closeDisabledTooltip:
        "Cypheus is building. Click 'Create new bot' to stop.",
      progressLabel: (current: number, total: number) =>
        `Step ${current} of ${total}`,
      summary: {
        title: 'All set ✓',
        reviewJson: 'Review JSON',
        close: 'Close',
      },
    },
    afterDone:
      'Demo complete. Click Create new bot to start over, or explore the configuration manually.',
    json: {
      emptyTitle: "Your bot's JSON will live here",
      emptySubtitle: 'Configure any step to see the live preview.',
      emptyCtaConfig: 'Open Bot Config',
      emptyCtaAsk: 'Ask Cypheus',
    },
    progress: {
      empty: 'Set up your bot to get started',
      // Phrase is now "phases" — widget aggregates 4 stepStatus IDs into
      // 2 phases (Bot Basics + Strategy). See Spec/Phase 1/two_phase_ui_plan.md.
      configured: (n: number) => `${n} / 2 phases configured`,
      issues: (n: number) => `${n} ${n === 1 ? 'issue' : 'issues'}`,
      issuesBlock: (n: number) =>
        `${n} ${n === 1 ? 'issue' : 'issues'} ${n === 1 ? 'blocks' : 'block'} export`,
      ready: 'Ready to export',
      fix: 'Fix',
      export: 'Export bot',
    },
  },
  steps: {
    botConfig: {
      title: 'Bot Config',
      description: 'Pick the market, timeframe and trading mode.',
    },
    entryStrategy: {
      title: 'Entry Strategy',
      description: 'Add indicators and define entry conditions.',
    },
    direction: {
      title: 'Direction & Order',
      description: 'Long or Short, market or limit.',
    },
    closeMethod: {
      title: 'Close Method',
      description: 'How and when the bot exits.',
    },
    addStrategy: {
      title: 'Add strategy',
      description: 'Multi-strategy support is on the way.',
      comingSoon: 'Coming soon',
    },
  },
  // 2-phase UI redesign — see Spec/Phase 1/two_phase_ui_plan.md.
  // Surface strings only; data layer still uses 4 stepStatus IDs.
  phase: {
    botBasics: {
      title: 'Bot Basics',
      description: 'Pick the market, timeframe and trading mode.',
    },
    strategy: {
      title: 'Strategy',
      description: 'Entry conditions, direction, and close method.',
    },
  },
  // Bot Summary widget — see Spec/Phase 1/bot_summary_plan.md.
  // The actual prose lines are generated by the rule-based translators
  // in src/features/bot-summary/translators/* — only chrome strings live
  // here so a future locale can swap card titles / collapse labels /
  // gap footers without touching translator code.
  botSummary: {
    title: 'What this bot does',
    pristineHint:
      'Setup not complete yet — finish the phases above to see what this bot will do.',
    sections: {
      market: 'Market',
      risk: 'Risk',
      entry: 'Entry',
      action: 'Action',
      exit: 'Exit',
      notifications: 'Notifications',
    },
    showDetails: (n: number) =>
      `Show details (${n} more line${n === 1 ? '' : 's'})`,
    hideDetails: 'Hide details',
    gapsHeader: (n: number) =>
      `Couldn't fully translate (${n} field${n === 1 ? '' : 's'}):`,
    gapsFooter: 'See the JSON tab for full configuration.',
    dismiss: 'Hide summary',
  },

  // Layout / view-prefs toggles in the HeaderToolbar — see
  // `useLayoutPrefsStore`. Persisted across reloads.
  layoutToggles: {
    cypheusShowAria: 'Show Cypheus panel',
    cypheusHideAria: 'Hide Cypheus panel',
    cypheusShowTooltip: 'Show Cypheus chat panel',
    cypheusHideTooltip: 'Hide Cypheus chat panel for more canvas room',
    summaryShowAria: 'Show bot summary',
    summaryHideAria: 'Hide bot summary',
    summaryShowTooltip: 'Show "What this bot does" widget',
    summaryHideTooltip: 'Hide "What this bot does" widget',
  },

  // Bot templates feature — see Spec/Phase 1/bot_templates_plan.md.
  templates: {
    headerButton: 'Templates',
    headerButtonAria: 'Browse bot templates',
    headerButtonTooltip: 'Pick a starter bot — Cypheus sets it up',

    emptyState: {
      cta: 'Browse templates',
      hint: 'Pick a template to skip setup, ask Cypheus, or build below.',
    },

    gallery: {
      title: 'Bot Templates',
      description: 'Pick a starter bot — fields fill instantly.',
      empty: 'No templates match this filter. Try clearing one of the chips above.',
      cardCypheusHint: 'Cypheus animates the setup',
      cardUseLabel: 'Use',
      cardUseAria: (name: string) => `Use ${name}`,
      cardPreviewAria: (name: string) => `Preview ${name}`,
    },

    detail: {
      cancel: 'Cancel',
      use: 'Use this template',
      useAria: (name: string) => `Use ${name}`,
      keyParams: 'Key parameters',
      params: {
        pair: 'Pair',
        timeframe: 'Timeframe',
        mode: 'Mode',
        direction: 'Direction',
        indicators: 'Indicators',
        close: 'Close',
      },
    },

    confirmReplace: {
      title: 'Replace your current bot?',
      body: (name: string) =>
        `Loading "${name}" will discard your unsaved changes. This can't be undone.`,
      cancel: 'Keep editing',
      confirm: 'Replace and load',
    },

    appliedBadge: {
      prefix: 'Based on',
      diverged: 'Diverged',
      viewDetails: 'View template details',
      resetAria: 'Reset to template snapshot',
      resetTooltip: 'Reset to template snapshot (instant — no animation).',
    },

    filter: {
      difficulty: 'Difficulty',
      risk: 'Risk',
      tag: 'Tag',
      difficultyOptions: {
        beginner: 'Beginner',
        intermediate: 'Intermediate',
        advanced: 'Advanced',
      },
      riskOptions: {
        conservative: 'Conservative',
        balanced: 'Balanced',
        aggressive: 'Aggressive',
      },
    },

    apply: {
      // Toast + chat copy used by snap-apply path.
      loadedToast: (name: string) => `Applied "${name}"`,
      loadedChat: (name: string) =>
        `Loaded "${name}". Ready to export.`,
    },

    openPhaseAria: (label: string) => `Open ${label} phase`,
  },

  strategyDrawer: {
    title: 'Strategy',
    description:
      'Define when the bot enters, which way it goes, and how it exits.',
    sections: {
      entry: 'Entry conditions',
      action: 'Action',
    },
    saveDisabledTooltip:
      'Fill the required fields in Entry conditions and Action to enable Save.',
  },
  // Phase 1 composite drawer — same single-pane pattern as strategy.
  // Header copy used when the drawer renders the merged Setup+Configure
  // form for `bot-config`.
  botConfigDrawer: {
    title: 'Bot Basics',
    description:
      'Pick the market, timeframe, trading mode and stake — all in one place.',
  },
  drawer: {
    setupTab: 'Setup',
    configureTab: 'Configure',
    cancel: 'Cancel',
    save: 'Save',
    saveAndNext: 'Save & Next →',
    saveAndFinish: 'Save & Finish',
    skipSave: 'Skip & Save',
    continueLabel: 'Continue →',
    back: '← Back',
    close: 'Close',
    stepLabel: (n: number) => `Step ${n}`,
    progressLabels: {
      setup: 'Setup',
      configure: 'Configure',
    },
    tooltips: {
      configureLocked: 'Complete Setup first to unlock Configure',
      continueDisabled: 'Fill all required fields in Setup',
      skipSave: 'Save with default Configure values. You can edit later.',
    },
    toasts: {
      configureLocked: 'Complete Setup first to unlock Configure',
    },
  },
} as const;

export type Strings = typeof strings;
