/**
 * All user-facing strings live here so we can swap to a different locale
 * (e.g. Vietnamese) without touching components.
 */
export const strings = {
  app: {
    title: 'Strategy Builder',
    subtitle: 'Design, configure and export your trading bot strategy.',
  },
  header: {
    botNamePlaceholder: 'Bot Basic',
    createBot: 'Create bot',
    saved: 'Saved',
    saving: 'Saving…',
    secondsAgo: (s: number) => `${s}s ago`,
  },
  cypheus: {
    panelTitle: 'Cypheus',
    comingSoonPill: 'Coming Soon',
    createNewBot: 'New',
    confirmReset: {
      title: 'Start a new bot?',
      body: 'Your current configuration will be cleared.',
      confirm: 'Start over',
      cancel: 'Cancel',
    },
    greeting: {
      hello: "Hi, I'm Cypheus.",
      pitch:
        "I'm your AI co-pilot — soon I'll be able to build trading bots from just a conversation.",
      comingSoon:
        '**Coming soon.** For now, pick a template or build manually with the step cards.',
    },
    progress: {
      empty: 'Set up your bot to get started',
      // Phrase is now "phases" — widget aggregates 4 stepStatus IDs into
      // 2 phases (Bot Basics + Strategy). See Spec/Phase 1/two_phase_ui_plan.md.
      configured: (n: number) => `${n} / 2 phases configured`,
      issues: (n: number) => `${n} ${n === 1 ? 'issue' : 'issues'}`,
      issuesBlock: (n: number) =>
        `${n} ${n === 1 ? 'issue' : 'issues'} ${n === 1 ? 'blocks' : 'block'} export`,
      ready: 'Ready to export',
      fix: 'Fix',
      export: 'Export bot',
    },
  },
  steps: {
    botConfig: {
      title: 'Bot Config',
      description: 'Pick the market, timeframe and stake configuration.',
    },
    entryStrategy: {
      title: 'Entry Strategy',
      description: 'Add indicators and define entry conditions.',
    },
    direction: {
      title: 'Direction & Order',
      description: 'Long or Short, market or limit.',
    },
    closeMethod: {
      title: 'Close Method',
      description: 'How and when the bot exits.',
    },
    addStrategy: {
      title: 'Add strategy',
      description: 'Multi-strategy support is on the way.',
      comingSoon: 'Coming soon',
    },
  },
  // 2-phase UI redesign — see Spec/Phase 1/two_phase_ui_plan.md.
  // Surface strings only; data layer still uses 4 stepStatus IDs.
  phase: {
    botBasics: {
      title: 'Bot Basics',
      description: 'Pick the market, timeframe and stake configuration.',
    },
    strategy: {
      title: 'Strategy',
      description: 'Entry conditions, direction, and close method.',
    },
  },
  // Bot Summary widget — see Spec/Phase 1/bot_summary_plan.md.
  // The actual prose lines are generated by the rule-based translators
  // in src/features/bot-summary/translators/* — only chrome strings live
  // here so a future locale can swap card titles / collapse labels /
  // gap footers without touching translator code.
  botSummary: {
    title: 'What this bot does',
    pristineHint:
      'Setup not complete yet — finish the phases above to see what this bot will do.',
    sections: {
      market: 'Market',
      risk: 'Risk',
      entry: 'Entry',
      action: 'Action',
      exit: 'Exit',
      notifications: 'Notifications',
    },
    showDetails: (n: number) =>
      `Show details (${n} more line${n === 1 ? '' : 's'})`,
    hideDetails: 'Hide details',
    gapsHeader: (n: number) =>
      `Couldn't fully translate (${n} field${n === 1 ? '' : 's'}):`,
    gapsFooter: 'See the JSON tab for full configuration.',
    dismiss: 'Hide summary',
  },

  // Layout / view-prefs toggles in the HeaderToolbar — see
  // `useLayoutPrefsStore`. Persisted across reloads.
  layoutToggles: {
    cypheusShowAria: 'Show Cypheus panel',
    cypheusHideAria: 'Hide Cypheus panel',
    cypheusShowTooltip: 'Show Cypheus chat panel',
    cypheusHideTooltip: 'Hide Cypheus chat panel for more canvas room',
    summaryShowAria: 'Show bot summary',
    summaryHideAria: 'Hide bot summary',
    summaryShowTooltip: 'Show "What this bot does" widget',
    summaryHideTooltip: 'Hide "What this bot does" widget',
    summaryModeVisualAria: 'Switch to narrative summary',
    summaryModeNarrativeAria: 'Switch to visual summary',
    summaryModeVisualTooltip: 'Plain English (sentence form)',
    summaryModeNarrativeTooltip: 'Compact visual (chips & data)',
  },

  // Bot templates feature — see Spec/Phase 1/bot_templates_plan.md.
  templates: {
    headerButton: 'Templates',
    headerButtonAria: 'Browse bot templates',
    headerButtonTooltip: 'Pick a starter bot — Cypheus sets it up',

    emptyState: {
      cta: 'Browse templates',
      hint: 'Pick a template to skip setup, ask Cypheus, or build below.',
    },

    gallery: {
      title: 'Bot Templates',
      description: 'Pick a starter bot — fields fill instantly.',
      empty:
        'No templates match this filter. Try clearing one of the chips above.',
      cardCypheusHint: 'Instant setup',
      cardUseLabel: 'Use',
      cardUseAria: (name: string) => `Use ${name}`,
      cardPreviewAria: (name: string) => `Preview ${name}`,
    },

    detail: {
      cancel: 'Cancel',
      use: 'Use this template',
      useAria: (name: string) => `Use ${name}`,
      keyParams: 'Key parameters',
      params: {
        pair: 'Pair',
        timeframe: 'Timeframe',
        mode: 'Mode',
        direction: 'Direction',
        indicators: 'Indicators',
        close: 'Close',
      },
    },

    confirmReplace: {
      title: 'Replace your current bot?',
      body: (name: string) =>
        `Loading "${name}" will discard your unsaved changes. This can't be undone.`,
      cancel: 'Keep editing',
      confirm: 'Replace and load',
    },

    appliedBadge: {
      prefix: 'Based on',
      diverged: 'Diverged',
      viewDetails: 'View template details',
      resetAria: 'Reset to template snapshot',
      resetTooltip: 'Reset to template snapshot (instant — no animation).',
    },

    filter: {
      difficulty: 'Difficulty',
      risk: 'Risk',
      tag: 'Tag',
      difficultyOptions: {
        beginner: 'Beginner',
        intermediate: 'Intermediate',
        advanced: 'Advanced',
      },
      riskOptions: {
        conservative: 'Conservative',
        balanced: 'Balanced',
        aggressive: 'Aggressive',
      },
    },

    apply: {
      // Toast + chat copy used by snap-apply path.
      loadedToast: (name: string) => `Applied "${name}"`,
      loadedChat: (name: string) => `Loaded "${name}". Ready to export.`,
      textViewHint:
        'Tip: view this strategy as text — use the toggle above the summary.',
    },

    openPhaseAria: (label: string) => `Open ${label} phase`,
  },

  strategyDrawer: {
    title: 'Strategy',
    description:
      'Define when the bot enters, which way it goes, and how it exits.',
    sections: {
      entry: 'Entry conditions',
      action: 'Action',
    },
    saveDisabledTooltip:
      'Fill the required fields in Entry conditions and Action to enable Save.',
  },
  // Phase 1 composite drawer — same single-pane pattern as strategy.
  // Header copy used when the drawer renders the merged Setup+Configure
  // form for `bot-config`.
  botConfigDrawer: {
    title: 'Bot Basics',
    description:
      'Pick the market, timeframe, leverage and stake — all in one place.',
  },
  drawer: {
    setupTab: 'Setup',
    configureTab: 'Configure',
    cancel: 'Cancel',
    save: 'Save',
    saveAndNext: 'Save & Next →',
    saveAndFinish: 'Save & Finish',
    skipSave: 'Skip & Save',
    continueLabel: 'Continue →',
    back: '← Back',
    close: 'Close',
    stepLabel: (n: number) => `Step ${n}`,
    progressLabels: {
      setup: 'Setup',
      configure: 'Configure',
    },
    tooltips: {
      configureLocked: 'Complete Setup first to unlock Configure',
      continueDisabled: 'Fill all required fields in Setup',
      skipSave: 'Save with default Configure values. You can edit later.',
    },
    toasts: {
      configureLocked: 'Complete Setup first to unlock Configure',
    },
  },
  /** Per-field help-text shown by FormField when the `help` prop is set.
   * Keep each string ≲ 25 words so it fits a single tooltip without
   * overflowing the max-w-xs container. */
  helpText: {
    botConfig: {
      botName:
        'Display name for your bot. Also used as the generated Python bot file name on the backend.',
      pair: 'Trading pair the bot will trade, e.g. BTC-USDC. Must exist on Hyperliquid.',
      timeframe:
        'Candle interval the bot analyses and trades on. Shorter timeframes produce more signals but more noise.',
      leverage:
        'Futures leverage from 1× to 50×. Higher leverage amplifies both gains and liquidation risk.',
      exchange:
        'Locked to Hyperliquid in this phase. Binance / Bybit will land later.',
      marketType:
        'Locked to Futures in this phase. Spot markets are not yet wired up end-to-end.',
      marginMode:
        'Cross shares margin across all positions in the account. Isolated walls each position off — one liquidation can’t touch the others.',
      maxOpenTrades:
        'Max number of positions the bot may hold at once. Set to -1 for unlimited.',
      stakeCurrency:
        'The quote currency used when staking a position (USDT / USDC / BUSD).',
      stakeAmount:
        'Amount of stake-currency committed per entry. Used as the position size when opening a trade.',
      dryRunWallet:
        'Virtual wallet balance used while in Dry-run mode. Has no effect once you switch to Live.',
    },
    strategy: {
      strategyName:
        'Display label for the entry strategy. Cosmetic — does not affect any backend logic.',
      indicators:
        'Indicators referenced in your entry conditions. They’re auto-added when you pick them in a rule; removing one will break any condition that uses it.',
      direction:
        'Long opens a buy expecting price up. Short opens a sell expecting price down.',
      orderType:
        'Market fills immediately at the best price. Limit waits for the price you set (with an offset).',
      limitOffset:
        'Percent offset from the current close. Positive moves the limit price away from current (further from fill); negative moves it closer.',
      closeMethod:
        'How the bot exits a position. Manual = you close it; TP / SL = take-profit & stop-loss; ROI = time-based ROI table. Toggle Advanced to enable Indicator-based exits.',
    },
    monitoring: {
      // Status & process
      state:
        'The bot’s live process state as last reported by the backend (running, stopped, error, …).',
      desiredStatus:
        'The state you asked for. The bot converges to this — a mismatch with State means it’s still transitioning.',
      process:
        'Whether the backend Freqtrade process is actually up. "down" while State is running means the process died.',
      lastHeartbeat:
        'Time since the bot last reported in. Stale heartbeats suggest the process is stuck or dead.',
      // Mode / config not covered by builder copy
      mode: 'Dry-run trades on a virtual wallet (no real funds). Live places real orders on the exchange.',
      tradingMode:
        'Spot trades the asset directly; Futures trades perpetual contracts with leverage.',
      // Backtest performance metrics
      netProfit:
        'Total profit/loss across all backtest trades, in stake currency. Negative = the strategy lost money.',
      trades:
        'Total number of trades the strategy opened and closed during the backtest window.',
      winRate:
        'Share of backtest trades that closed in profit. High win rate alone doesn’t guarantee net profit.',
      profitFactor:
        'Gross profit ÷ gross loss. Above 1 means winners outweigh losers; below 1 is a losing strategy.',
      sharpe:
        'Risk-adjusted return — return per unit of total volatility. Higher is better; below 0 is poor.',
      sortino:
        'Like Sharpe but only penalises downside volatility. Higher is better.',
      maxDrawdown:
        'Largest peak-to-trough drop in equity during the backtest. Lower is safer.',
      tradesPerDay:
        'Average number of trades opened per day over the backtest window.',
      avgTrade:
        'Average time a position stays open, from entry to exit, across all backtest trades.',
      exitReason:
        'Why each trade closed — e.g. force_exit (cut off at the backtest window end), roi, stop_loss, trailing stop, or exit_signal.',
      // Hero KPIs
      openTrades:
        'Positions the bot holds right now, against its max-open-trades cap.',
      winRateBt:
        'Win rate from the selected backtest run — historical, not live performance.',
      netBt:
        'Net profit from the selected backtest run — historical, not live performance.',
    },
  },
  closeMethod: {
    advancedLabel: 'Advanced',
    advancedTooltip:
      'Reveal the Indicator tab — exit when a custom indicator condition fires (trend-follow, mean-reversion). Hidden by default to keep the picker compact.',
    newBadge: 'NEW',
  },
  // Telegram notifications section in the Strategy drawer. Ticking the
  // toggle + filling token/chat ID makes the create payload ship a valid
  // `telegram` block (instead of null). Test-flow feature.
  notifications: {
    sectionTitle: 'Notifications',
    telegramToggle: 'Send Telegram notifications',
    telegramHelp:
      'When on, the created bot reports entries, exits and errors to your Telegram chat. Token + chat ID are baked into the bot on create.',
    tokenLabel: 'Bot token',
    tokenPlaceholder: 'Paste your bot token',
    chatIdLabel: 'Chat ID',
    chatIdPlaceholder: 'e.g. 123456789',
    // Inline warning shown under the inputs inside the Notifications section.
    required: 'Enter bot token and chat ID to enable.',
    // Same rule surfaced as a builder issue — shown on a step card / Cypheus
    // list away from the Notifications section, so it needs the "Telegram:"
    // prefix to self-explain.
    requiredIssue: 'Telegram: enter bot token and chat ID to enable.',
    // Deploy-modal recap line prefix (chat ID is appended in a styled span).
    recapPrefix: 'Telegram → chat',
  },
} as const;

export type Strings = typeof strings;
